### ISSUE TITLE
java compatability oracle java 

### ISSUE THREAD

**Issue by rlindauer** [IG-Group/ig-orchestrations#8]
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (generate-markdown) on project document-fixt: An exception occured while executing the Java class. io/fixprotocol/orchestra2md/Orchestra2md has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :document-fixt
[rlindauer@balboa ig-orchestrations]$ java --version
java 16.0.1 2021-04-20
Java(TM) SE Runtime Environment (build 16.0.1+9-24)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)

**Comment by matthew-peacock-ig** [comment]
Hi @rlindauer 
Thank you for posting your issue on our github project!
Apologies for not replying sooner. We gave some feedback through another channel so I am not sure if you are still facing this issue?
The issue sounds like your version of java maven is using may be jdk8. Can you try running executing mvn -version to verify the java version maven is using? The version needs to be jdk11 or later.
Thanks
